image: maven:latest

stages:
    - Build
    - Test
    - Deploy
    - Deliver

build:
  stage: Build
  script:
    - mvn -B -DskipTests clean package

test:
  stage: Test
  script:
    - mvn test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/*.xml

deploy:
  stage: Deploy
  script:
    - mvn -B -DskipTests -s settings.xml clean deploy

deliver:
    stage: Deliver
    script:
        - mvn -B -DskipTests clean package
        - chmod a+x ci/scripts/deliver.sh
        - ./ci/scripts/deliver.sh
