pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*xml'
                }
            }
        }
        stage('Deploy') {
            steps{
                sh 'mvn -B -DskipTests -s settings.xml clean deploy'
            }
        }
        stage('Deliver') {
            steps {
                sh 'chmod a+x ci/scripts/deliver.sh'
                sh './ci/scripts/deliver.sh'
            }
        }
    }
}
